# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'MatchupMatchApp_3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  # Pods for MatchupMatchApp_3

  target 'MatchupMatchApp_3-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MatchupMatchApp_3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
